### ISSUE TITLE
Fix the build!

### ISSUE THREAD

**Issue by wimjongman** [eclipse-mylyn/.github#1]
The first order of business is to fix the build.

- [x]  mylyn-commons (https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/4)
- [x]  mylyn-tasks (https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/4)
- [x]  mylyn-contexts (https://github.com/eclipse-mylyn/org.eclipse.mylyn.context/issues/7)
- [x]  mylyn-versions (https://github.com/eclipse-mylyn/org.eclipse.mylyn.versions/issues/4)
- [x]  mylyn-builds (https://github.com/eclipse-mylyn/org.eclipse.mylyn.builds/issues/4)
- [x]  mylyn-reviews (https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/3)
- [x]  mylyn (https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/2)

After this, let's take a look at the GH actions.

**Comment by ruspl-afed** [comment]
* CI/CD now works for `mylyn-commons` see https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/4
* CI/CD now works for `mylyn-tasks` see https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/4
`mylyn-context` could be the next one, but Mylyn dependencies are unpredictable.

**Comment by BeckerFrank** [comment]
>   `mylyn-context` could be the next one, but Mylyn dependencies are unpredictable.

Yes `mylyn-context`  could be the next one, maybe we only can get problems with `org.eclipse.mylyn.bugzilla.ide` but I think the reference is only from within the plugin.xml

**Comment by ruspl-afed** [comment]
CI/CD now works for `mylyn-context` see https://github.com/eclipse-mylyn/org.eclipse.mylyn.context/issues/7

**Comment by ruspl-afed** [comment]
CI/CD now works for mylyn-versions see https://github.com/eclipse-mylyn/org.eclipse.mylyn.versions/issues/4

**Comment by ruspl-afed** [comment]
CI/CD now works for mylyn-builds see https://github.com/eclipse-mylyn/org.eclipse.mylyn.builds/issues/4

**Comment by ruspl-afed** [comment]
CI/CD now works for mylyn-reviews see https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/3

**Comment by ruspl-afed** [comment]
ok, we have CI working for `master` branch

**Comment by wimjongman** [comment]
Thanks!
