### ISSUE TITLE
Create a build to promote a release

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/.github#23]
We need a release candidate build that upload binaries in a form of p2 repository that can be installed to an Eclipse product (let's say EPP for Committers) without troubles.

**Comment by ruspl-afed** [comment]
I've created a 3.26.0 RC1 build https://download.eclipse.org/mylyn/stage/milestone/3.26.0-RC1/
Any comments are welcome @BeckerFrank @wimjongman

**Comment by BeckerFrank** [comment]
I did a first install in a fresh 2023-03 Commiter Eclipse installation and a first test shows no problems.
One thing is that the bundles are not signed so we get the trust dialog. 
Can we add signatures for the bundles?
Will continue with some more tests.

**Comment by ruspl-afed** [comment]
> One thing is that the bundles are not signed so we get the trust dialog.

Thank you for reporting @BeckerFrank I'll have a look

**Comment by ruspl-afed** [comment]
Build was fully recreated, here is the result https://download.eclipse.org/mylyn/stage/latest/

**Comment by BeckerFrank** [comment]
Maybe we can find what we need to change so that the last 5 org.eclipse.mylyn.* bundles are trusted 
![image](https://user-images.githubusercontent.com/13169360/235411092-6c7ed84f-5808-496a-babe-396630b7cc22.png)

**Comment by ruspl-afed** [comment]
I've downloaded `org.eclipse.mylyn_feature_3.26.0.N20230416-1636.jar` to examine its content and I can see `ECLIPSE_.RSA` and `ECLIPSE_.SF` files inside `META-INF` directory.

@merks what else should be done to make installation process happy?

**Comment by merks** [comment]
This issue of generating OSGi artifacts from Maven artifacts is of great concern to me:

https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/103

According to this report there are only 4 unsigned artifacts:

https://download.eclipse.org/oomph/archive/reports-extra/mylyn/download.eclipse.org/mylyn/stage/latest/index.html

If you're going to pull dependencies directly from Maven you will need to enable PGP signing in your builds.  This has been discussed repeatedly on cross projects for years...

Probably the above issue with org.eclipse.mylyn.* artifacts is the result of having older unsigned versions in the bundle pool that have the exact same artifact key as the newer signed versions.  This is why it's never good to allow unsigned artifacts to escape into the wild, i.e., available on download.eclipse.org, because they are impossible to stamp them out except to provide at least a new qualifier version.

**Comment by merks** [comment]
Which target are you using for your builds?  It's easier to help if I know which target file needs attention...

**Comment by ruspl-afed** [comment]
This is what we use:
https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/org.eclipse.mylyn-target/mylyn-e4.26.target

I can try to redirect com.sun/javax/jakarta back to orbit, but we do not have enough Lucene libs there

**Comment by merks** [comment]
Yes, I see these all fail:

![image](https://user-images.githubusercontent.com/208716/235422646-14c7fa38-7eb2-492a-bb77-05c1062954d5.png)

And I don't see Orbit versions of all of these...

**Comment by ruspl-afed** [comment]
Yes, we don't have them in Orbit. And even if I'll push Mylyn team to degrade back to Lucene 9.4.2 we still have no Lucene Query Parser 9.4.2 in Orbit.
What should I do to propose Lucene (and Mockito) for the "centralized" location?

**Comment by merks** [comment]
I've already been prototyping producing generated direct-from-maven from m2e targets so I have something working locally already:

![image](https://user-images.githubusercontent.com/208716/235431734-de166bf8-8077-45ff-ba67-f96690d25bf3.png)

I've been using this recipe where the imports are not optional:
```
		  <instructions><![CDATA[
Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   ${mvnGroupId}.${mvnArtifactId}
Bundle-Version:        ${version}
Import-Package:        *
Export-Package:        *;version="${version}";-noimport:=true
DynamicImport-Package: *
]]></instructions>
```

I'm very concerned though that you are generating a **release**, not just a **milestone** so any mistakes now will be etched in stone.   Also, once this IU is published and available, I cannot change the recipe without some version change, and I'm not 100% sure this is the exact best recipe.   See this comment about that concern:

https://github.com/merks/simrel-maven/issues/4#issuecomment-1510740227

In Orbit, each bundle had its own specialized BND recipe and qualifier versions were created so if the recipe changed, there would be a new version.  Also, it's not entirely clear if we should jar sign these things or PGP sign them.  The point of PGP signing was that we didn't want to modify the original artifact as provided by Maven, but that argument doesn't apply when we create a modified artifact...

We'd certainly all be better off if there was a bit more runway here for takeoff...

**Comment by merks** [comment]
BTW, I am assuming all the other m2e-location dependencies you can get from here:

https://download.eclipse.org/oomph/simrel-orbit/milestone/S202304261239/index.html

**Comment by merks** [comment]
I'm also investigating the direct-from-maven dependencies that are OSGi bundles.  These versions are not the latest:

## Minor Updates
 - [com.sun.xml.bind](https://repo1.maven.org/maven2/com/sun/xml/bind/)
    - [jaxb-impl](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/) **[2.3.3](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3)** < [2.3.8](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.8/)
 - [org.mockito](https://repo1.maven.org/maven2/org/mockito/)
    - [mockito-inline](https://repo1.maven.org/maven2/org/mockito/mockito-inline/) **[4.8.1](https://repo1.maven.org/maven2/org/mockito/mockito-inline/4.8.1)** < [4.11.0](https://repo1.maven.org/maven2/org/mockito/mockito-inline/4.11.0/)

I don't have a good sense of whether all these requires are actually needed

## Major Updates
 - [com.sun.xml.bind](https://repo1.maven.org/maven2/com/sun/xml/bind/)
    - [jaxb-impl](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/) **[2.3.3](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3)** < [4.0.2](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/4.0.2/)
 - [jakarta.xml.bind](https://repo1.maven.org/maven2/jakarta/xml/bind/)
    - [jakarta.xml.bind-api](https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/) **[2.3.3](https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3)** < [4.0.0](https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/4.0.0/)
 - [org.mockito](https://repo1.maven.org/maven2/org/mockito/)
    - [mockito-inline](https://repo1.maven.org/maven2/org/mockito/mockito-inline/) **[4.8.1](https://repo1.maven.org/maven2/org/mockito/mockito-inline/4.8.1)** < [5.2.0](https://repo1.maven.org/maven2/org/mockito/mockito-inline/5.2.0/)

## Content
 - [com.sun.activation](https://repo1.maven.org/maven2/com/sun/activation/)
    - [jakarta.activation](https://repo1.maven.org/maven2/com/sun/activation/jakarta.activation/) **[2.0.1](https://repo1.maven.org/maven2/com/sun/activation/jakarta.activation/2.0.1)**
 - [com.sun.xml.bind](https://repo1.maven.org/maven2/com/sun/xml/bind/)
    - [jaxb-impl](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/) **[2.3.3](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3)**
 - [jakarta.xml.bind](https://repo1.maven.org/maven2/jakarta/xml/bind/)
    - [jakarta.xml.bind-api](https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/) **[2.3.3](https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3)**
 - [org.apache.lucene](https://repo1.maven.org/maven2/org/apache/lucene/)
    - [lucene-analysis-common](https://repo1.maven.org/maven2/org/apache/lucene/lucene-analysis-common/) **[9.5.0](https://repo1.maven.org/maven2/org/apache/lucene/lucene-analysis-common/9.5.0)**
    - [lucene-core](https://repo1.maven.org/maven2/org/apache/lucene/lucene-core/) **[9.5.0](https://repo1.maven.org/maven2/org/apache/lucene/lucene-core/9.5.0)**
    - [lucene-queryparser](https://repo1.maven.org/maven2/org/apache/lucene/lucene-queryparser/) **[9.5.0](https://repo1.maven.org/maven2/org/apache/lucene/lucene-queryparser/9.5.0)**
 - [org.eclipse.mylyn.github](https://repo1.maven.org/maven2/org/eclipse/mylyn/github/)
    - [org.eclipse.egit.github.core](https://repo1.maven.org/maven2/org/eclipse/mylyn/github/org.eclipse.egit.github.core/) **[6.1.0.202203080745-r](https://repo1.maven.org/maven2/org/eclipse/mylyn/github/org.eclipse.egit.github.core/6.1.0.202203080745-r)**
 - [org.glassfish.hk2](https://repo1.maven.org/maven2/org/glassfish/hk2/)
    - [osgi-resource-locator](https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/) **[2.4.0](https://repo1.maven.org/maven2/org/glassfish/hk2/osgi-resource-locator/2.4.0)**
 - [org.mockito](https://repo1.maven.org/maven2/org/mockito/)
    - [mockito-inline](https://repo1.maven.org/maven2/org/mockito/mockito-inline/) **[4.8.1](https://repo1.maven.org/maven2/org/mockito/mockito-inline/4.8.1)**

**Comment by merks** [comment]
I updated the available minor updates and now I look at what is transitively pulled in:

![image](https://user-images.githubusercontent.com/208716/235444094-0678c5c1-436e-4a19-bb73-2e0119f8429b.png)

If I change to just `includeDependencyScopes="compile"` there are fewer things:

![image](https://user-images.githubusercontent.com/208716/235444286-02ab51f0-28ea-4ab4-a35d-8ef37bf4958a.png)

If I change `includeDependencyDepth="none"` there are of course only the direct things:

![image](https://user-images.githubusercontent.com/208716/235444547-f8e28812-cc6e-41bb-9e61-0475a660ac87.png)

But even in this case, there are no errors in the workspace and the Tycho build gets almost to the end:

> [INFO] org.eclipse.mylyn.tests 3.26.0-SNAPSHOT ............ FAILURE [  1.512 s]
> [INFO] Mylyn for Eclipse 4.x 3.26.0-SNAPSHOT .............. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  01:32 min
> [INFO] Finished at: 2023-05-01T13:13:46+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR]

I skipped the tests because they abort probably because I'm on Windows, but who knows...

Even commenting some of them out does not result in errors in the workspace and the build gets to the same point:

![image](https://user-images.githubusercontent.com/208716/235445107-20e33966-4a66-47a9-a75c-26710e230022.png)


I'm really uncomfortable not understanding what's here that's strictly required and even with a recipe that does this where it's valid for all packages to simply be missing even though it's highly unlikely to be true:
```
Import-Package:        *;resolution:=optional
```

**Comment by ruspl-afed** [comment]
jaxb-impl is used on runtime, it will not fail during compilation. perhaps some tests could fail, but I do not know for sure.

I do not insist on recipe directives, it could have got there from another "already working" eclipse project without too much understanding what exactly it does.

could you please formulate your changes as a PR, the most interesting parts are
1) lucene
2) mockito

for jaxb/activation I hope to use either Orbit or what Platform is used

For EGit we already have work in progress [here](https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/104)

**Comment by merks** [comment]
That sounds like a good plan.

**Comment by wimjongman** [comment]
I saw your beautiful update sites, Ed, but did not realize that this was already generalized. Is this something that could go in Tycho? @laeubi

**Comment by merks** [comment]
Here’s an example of how it’s integrated into a Tycho build. 

https://github.com/eclipse-cbi/targetplatform-dsl/blob/01c3a1c1cdbf511d804cf08caa76e2364a02e2ee/promotion/pom.xml#L30

Here’s how most of the builds are configured:

https://github.com/eclipse-cbi/targetplatform-dsl/blob/01c3a1c1cdbf511d804cf08caa76e2364a02e2ee/promotion/pom.xml#L30

Lots of commented out stuff in that one…

**Comment by ruspl-afed** [comment]
I updated https://download.eclipse.org/mylyn/stage/latest/ to include latest changes for 3rd party libs

**Comment by merks** [comment]
I’ll test it later when I’m home but no reason to expect any problems.

**Comment by ruspl-afed** [comment]
I created https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/110 to fix report issues

**Comment by ruspl-afed** [comment]
I updated https://download.eclipse.org/mylyn/stage/latest/ to include latest changes:

1) https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/110
2) https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/111
3) https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/108

**Comment by merks** [comment]
It looks better 

https://download.eclipse.org/oomph/archive/reports-extra/mylyn/download.eclipse.org/mylyn/stage/latest/index.html

**Comment by ruspl-afed** [comment]
Good, but we have failures during SimRel validation, it seems that I need to publish more required 3rd party libs to Mylyn repository

**Comment by ruspl-afed** [comment]
Created https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/114 to resolve this

**Comment by ruspl-afed** [comment]
Done, see https://download.eclipse.org/mylyn/drops/3.26.0/v20230503-2157/
