### ISSUE TITLE
Schedule release review for 3.26.0

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/.github#24]
Let's select a date for release and schedule release review @wimjongman @BeckerFrank

**Comment by BeckerFrank** [comment]
What's about if we try to to the release between 04/28 to 05/05 (simrel 2023-06 M2) and try to join the simrel for 2023-06 M3 (05/19 to 05/26)?

**Comment by wimjongman** [comment]
Yes sounds good to me.

Best regards,

Wim Jongman
________________________________

**Comment by ruspl-afed** [comment]
Release is a process, and we need to fit it. I've created a [Release Record](https://projects.eclipse.org/projects/tools.mylyn/releases/3.26.0) for the nearest available date, it is 4th of May  
Also, I've asked EMO to schedule a [Release Review](https://projects.eclipse.org/projects/tools.mylyn/reviews/3.26.0-release-review) for Mylyn 3.26.0
