### ISSUE TITLE
https://github.com/eclipse-mylyn refers to "this current repositories"

### ISSUE THREAD

**Issue by Chealer** [eclipse-mylyn/.github#31]
The Eclipse Mylyn homepage on GitHub contains the following paragraph in [its _Reporting issues_ section](https://github.com/eclipse-mylyn#reporting-issues):

> If you face an issue and have a sense of which particular GitHub repository is most related, you can open your issue against that repository. If you're unsure, you can open an issue against **this current repositories** and the issue will then be moved as best by maintainers.

This paragraph comes from [a README.md file part of the https://github.com/eclipse-mylyn/.github/ repository](https://github.com/eclipse-mylyn/.github/blob/main/profile/README.md), but when displaying the content on the homepage, it is unclear what "this current repositories" means, since the page is not part of any repository.

By the way:

1. "this current repositories" is incoherent number-wise, since "this" is singular while "repositories" is plural.
2. an issue cannot be "opened" or "moved". You surely mean s/_open your/an issue_/_report your/an issue_/ and s/_the issue will then be moved_/_the ticket will then be reassigned_/.

**Comment by wimjongman** [comment]
Yes, that is what we mean.

**Comment by wimjongman** [comment]
Fixed
