### ISSUE TITLE
README claims Mylyn averages 1 million downloads/month

### ISSUE THREAD

**Issue by Chealer** [eclipse-mylyn/.github#32]
According to [the README](https://github.com/eclipse-mylyn/.github/blob/main/profile/README.md) and [the homepage](https://eclipse.dev/mylyn/), Mylyn would be downloaded 1 million times/month on average:

> Mylyn provides:
> 
> -  The revolutionary task-focused interface
>     Realigns the IDE around tasks so that you see only the code that's relevant
> - A task management tool for developers
>   **Averaging 1 million downloads/month, Mylyn** is the most popular IDE tool for DevOps

[The statistics I can find](https://marketplace.eclipse.org/content/mylyn) are not too clear for me but rather suggest less than 1000 downloads/month in the latest months, making the claim highly questionable. Please refresh the stats, indicate on which period they were measured or/and provide a reference.

By the way:

- Sentences should be terminated with a period (".").
- The term "DevOps" is nearing the end of its hype cycle. Even if the term "IDE tool for DevOps" makes sense and Mylyn was actually "the most popular IDE tool for DevOps", it's probably better to avoid it at this point.

**Comment by wimjongman** [comment]
Yes, you are right. Are you able to make a PR? 

Source is here: https://github.com/eclipse-mylyn/mylyn-website

**Comment by wimjongman** [comment]
I fixed the README

**Comment by Chealer** [comment]
Thank you @wimjongman
