### ISSUE TITLE
Update version numbers to 3.26.0 for features and bundles

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/.github#7]
All the features should be aligned to version numbers to 3.26.0 
* to simplify support
* to identify circular dependencies

- [x]  mylyn-commons (https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/25)
- [x]  mylyn-tasks (https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/9)
- [x]  mylyn-contexts (https://github.com/eclipse-mylyn/org.eclipse.mylyn.context/issues/12)
- [x]  mylyn-versions (https://github.com/eclipse-mylyn/org.eclipse.mylyn.versions/issues/6)
- [x]  mylyn-build (https://github.com/eclipse-mylyn/org.eclipse.mylyn.builds/issues/6)
- [x]  mylyn-reviews (https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/6)
- [x]  mylyn

**Comment by ruspl-afed** [comment]
We have an exception: `org.eclipse.cdt.mylyn` is already `5.22.0` and we cannot descrease it. 
But we can correct its name to `org.eclipse.mylyn.cdt` and give it version `3.26.0`
And this change would be a kind of breaking. WDYT @wimjongman @BeckerFrank ?

**Comment by wimjongman** [comment]
Is that a feature or a plugin? I am not so much looking at plugin versions but at feature versions. At least, this is the strategy I follow for other projects. If all plugins are on the same version, we can consider a mass replace, otherwise, maybe only use the features as release number indicators. WDYT?

**Comment by ruspl-afed** [comment]
> Is that a feature or a plugin?

https://github.com/eclipse-mylyn/org.eclipse.mylyn.context/blob/master/org.eclipse.mylyn.cdt-feature/feature.xml#L17

>  If all plugins are on the same version, we can consider a mass replace

This is exactly what I'm trying to achieve.

>> But we can correct its name to org.eclipse.mylyn.cdt and give it version 3.26.0

So, what about this proposal?

**Comment by wimjongman** [comment]
> So, what about this proposal?

That sounds good to me but what about the old feature? Will we ditch it?

There are 6k references to it on Github:  https://github.com/search?q=org.eclipse.cdt.mylyn&type=code

**Comment by ruspl-afed** [comment]
> Will we ditch it? There are 6k references to it on Github

It seems we can't do this. Let's mark it deprecated and keep if for some years.

**Comment by BeckerFrank** [comment]
Here is the file which we use to update the versions
[/org.eclipse.mylyn.releng/bin/update-versions.sh](https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/master/org.eclipse.mylyn.releng/bin/update-versions.sh)
so we can handle the different versions

**Comment by BeckerFrank** [comment]
I only want to point you to that script so that you can find all the parts that need to be changed.

**Comment by ruspl-afed** [comment]
Seems to be done with known exceptions like CDT
